# --- CONFIGURAÇÕES GLOBAIS (VARIÁVEIS) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-full-config
  namespace: default
data:
  # BANCO DE DADOS
  POSTGRES_DB: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD: "MudeSuaSenhaDbAqui123" # <--- SENHA DO DB
  DB_URL: "postgres://postgres:MudeSuaSenhaDbAqui123@supabase-db:5432/postgres"

  # SEGURANÇA (JWT) - Gere novos em https://jwt.io se for produção
  # Estes precisam ser IGUAIS em todos os serviços
  JWT_SECRET: "super-secret-jwt-token-with-at-least-32-characters-long"
  ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNjEyMDQ4MDAwLCJleHAiOjE5Mjc2MDgwMDB9.FakeSignatureForLabOnlyReplaceMe"
  SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE2MTIwNDgwMDAsImV4cCI6MTkyNzYwODAwMH0.FakeSignatureForLabOnlyReplaceMe"

  # URLS EXTERNAS (Para os serviços saberem onde eles moram)
  API_EXTERNAL_URL: "https://supabase.<<seu-dominio>>"
  GOTRUE_EXTERNAL_URL: "https://supabase.<<seu-dominio>>/auth/v1"
  STORAGE_EXTERNAL_URL: "https://supabase.<<seu-dominio>>/storage/v1"

---
# --- MIDDLEWARES TRAEFIK (PARA ROTEAMENTO AVANÇADO) ---
# Remove o prefixo da URL antes de enviar pro container
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-auth
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /auth/v1
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-rest
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /rest/v1
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-storage
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /storage/v1

---
# --- 1. POSTGRES (BANCO) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-db-full-data
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-db
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: supabase-db } }
  template:
    metadata: { labels: { app: supabase-db } }
    spec:
      containers:
        - name: db
          image: supabase/postgres:15.1.0.61
          ports: [{ containerPort: 5432 }]
          envFrom: [{ configMapRef: { name: supabase-full-config } }]
          volumeMounts: [{ name: db-data, mountPath: /var/lib/postgresql/data }]
          # Tuning leve para não estourar a RAM
          args:
            [
              "-c",
              "config_file=/etc/postgresql/postgresql.conf",
              "-c",
              "max_connections=100",
              "-c",
              "shared_buffers=512MB",
            ]
      volumes:
        [
          {
            name: db-data,
            persistentVolumeClaim: { claimName: supabase-db-full-data },
          },
        ]
---
apiVersion: v1
kind: Service
metadata: { name: supabase-db, namespace: default }
spec:
  ports: [{ port: 5432, targetPort: 5432 }]
  selector: { app: supabase-db }

---
# --- 2. GOTRUE (AUTH SERVICE) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-auth
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: supabase-auth } }
  template:
    metadata: { labels: { app: supabase-auth } }
    spec:
      containers:
        - name: auth
          image: supabase/gotrue:v2.132.3
          ports: [{ containerPort: 9999 }]
          env:
            - { name: GOTRUE_API_HOST, value: "0.0.0.0" }
            - { name: GOTRUE_API_PORT, value: "9999" }
            - { name: GOTRUE_DB_DRIVER, value: "postgres" }
            - {
                name: GOTRUE_DB_DATABASE_URL,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: DB_URL },
                  },
              }
            - {
                name: GOTRUE_SITE_URL,
                value: "https://supabase.<<seu-dominio>>",
              }
            - {
                name: GOTRUE_JWT_SECRET,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: JWT_SECRET },
                  },
              }
            - { name: GOTRUE_JWT_EXP, value: "3600" }
            - {
                name: GOTRUE_EXTERNAL_URL,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: GOTRUE_EXTERNAL_URL },
                  },
              }
---
apiVersion: v1
kind: Service
metadata: { name: supabase-auth, namespace: default }
spec:
  ports: [{ port: 80, targetPort: 9999 }]
  selector: { app: supabase-auth }

---
# --- 3. POSTGREST (API REST) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: supabase-rest } }
  template:
    metadata: { labels: { app: supabase-rest } }
    spec:
      containers:
        - name: rest
          image: postgrest/postgrest:v10.0.0
          ports: [{ containerPort: 3000 }]
          env:
            - {
                name: PGRST_DB_URI,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: DB_URL },
                  },
              }
            - { name: PGRST_DB_SCHEMA, value: "public,storage" }
            - { name: PGRST_DB_ANON_ROLE, value: "anon" }
            - {
                name: PGRST_JWT_SECRET,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: JWT_SECRET },
                  },
              }
---
apiVersion: v1
kind: Service
metadata: { name: supabase-rest, namespace: default }
spec:
  ports: [{ port: 80, targetPort: 3000 }]
  selector: { app: supabase-rest }

---
# --- 4. REALTIME (WEBSOCKETS) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-realtime
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: supabase-realtime } }
  template:
    metadata: { labels: { app: supabase-realtime } }
    spec:
      containers:
        - name: realtime
          image: supabase/realtime:v2.25.22
          ports: [{ containerPort: 4000 }]
          env:
            - { name: PORT, value: "4000" }
            - { name: DB_HOST, value: "supabase-db" }
            - { name: DB_PORT, value: "5432" }
            - { name: DB_USER, value: "postgres" }
            - {
                name: DB_PASSWORD,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: POSTGRES_PASSWORD },
                  },
              }
            - { name: DB_NAME, value: "postgres" }
            - { name: DB_SSL, value: "false" }
            - { name: SLOT_NAME, value: "supabase_realtime_rls" }
            - {
                name: JWT_SECRET,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: JWT_SECRET },
                  },
              }
---
apiVersion: v1
kind: Service
metadata: { name: supabase-realtime, namespace: default }
spec:
  ports: [{ port: 80, targetPort: 4000 }]
  selector: { app: supabase-realtime }

---
# --- 5. STORAGE (ARQUIVOS) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-storage-data
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-storage
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: supabase-storage } }
  template:
    metadata: { labels: { app: supabase-storage } }
    spec:
      containers:
        - name: storage
          image: supabase/storage-api:v1.0.3
          ports: [{ containerPort: 5000 }]
          env:
            - { name: POSTGREST_URL, value: "http://supabase-rest:3000" }
            - {
                name: PGRST_JWT_SECRET,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: JWT_SECRET },
                  },
              }
            - {
                name: DATABASE_URL,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: DB_URL },
                  },
              }
            - { name: FILE_STORAGE_BACKEND_PATH, value: "/var/lib/storage" }
            - { name: TENANT_ID, value: "stub" }
            - { name: REGION, value: "stub" }
            - { name: GLOBAL_S3_BUCKET, value: "stub" }
          volumeMounts: [{ name: storage-data, mountPath: /var/lib/storage }]
      volumes:
        [
          {
            name: storage-data,
            persistentVolumeClaim: { claimName: supabase-storage-data },
          },
        ]
---
apiVersion: v1
kind: Service
metadata: { name: supabase-storage, namespace: default }
spec:
  ports: [{ port: 80, targetPort: 5000 }]
  selector: { app: supabase-storage }

---
# --- 6. POSTGRES META (GERENCIADOR) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-meta
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: supabase-meta } }
  template:
    metadata: { labels: { app: supabase-meta } }
    spec:
      containers:
        - name: meta
          image: supabase/postgres-meta:v0.60.6
          ports: [{ containerPort: 8080 }]
          env:
            - {
                name: PG_META_DB_URL,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: DB_URL },
                  },
              }
---
apiVersion: v1
kind: Service
metadata: { name: supabase-meta, namespace: default }
spec:
  ports: [{ port: 80, targetPort: 8080 }]
  selector: { app: supabase-meta }

---
# --- 7. STUDIO (INTERFACE) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-studio
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: supabase-studio } }
  template:
    metadata: { labels: { app: supabase-studio } }
    spec:
      containers:
        - name: studio
          image: supabase/studio:20240101-83785f8
          ports: [{ containerPort: 3000 }]
          env:
            - { name: STUDIO_PG_META_URL, value: "http://supabase-meta:8080" }
            - { name: SUPABASE_URL, value: "http://supabase-rest:3000" }
            - {
                name: SUPABASE_PUBLIC_URL,
                value: "https://supabase.<<seu-dominio>>",
              }
            - {
                name: SUPABASE_ANON_KEY,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: ANON_KEY },
                  },
              }
            - {
                name: SUPABASE_SERVICE_KEY,
                valueFrom:
                  {
                    configMapKeyRef:
                      { name: supabase-full-config, key: SERVICE_ROLE_KEY },
                  },
              }
---
apiVersion: v1
kind: Service
metadata: { name: supabase-studio-svc, namespace: default }
spec:
  ports: [{ port: 3000, targetPort: 3000 }]
  selector: { app: supabase-studio }

---
# --- 8. INGRESS (ROTEAMENTO INTELIGENTE) ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supabase-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: portainer-force-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: supabase.<<seu-dominio>> # <---MUDE AQUI
      http:
        paths:
          # Rota para Auth (Login) -> usa middleware para remover /auth/v1
          - path: /auth/v1
            pathType: Prefix
            backend:
              service:
                name: supabase-auth
                port: { number: 80 }

          # Rota para REST API -> usa middleware para remover /rest/v1
          - path: /rest/v1
            pathType: Prefix
            backend:
              service:
                name: supabase-rest
                port: { number: 80 }

          # Rota para Storage -> usa middleware para remover /storage/v1
          - path: /storage/v1
            pathType: Prefix
            backend:
              service:
                name: supabase-storage
                port: { number: 80 }

          # Rota para Realtime (Websocket)
          - path: /realtime/v1
            pathType: Prefix
            backend:
              service:
                name: supabase-realtime
                port: { number: 80 }

          # Rota Padrão (Studio/UI) - Cai aqui se não for nenhuma acima
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supabase-studio-svc
                port: { number: 3000 }
